# Generated by Django 4.2.5 on 2023-11-07 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bank_card_number', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('Financial', 'Фінансова допомога'), ('Material', 'Матеріальна допомога')], default='Financial', max_length=64)),
                ('status', models.CharField(choices=[('ACTUAL', 'Актуальна'), ('PROVIDED', 'Завершена')], default='ACTUAL', max_length=64)),
                ('status_of_help', models.CharField(max_length=255)),
                ('contain_of_help', models.TextField()),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EXPECTED', 'Очікується допомога'), ('PROVIDED', 'Допомога надана'), ('CONFIRMED', 'Допомога підтверджена')], default='EXPECTED', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.donor')),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.helprequest')),
            ],
        ),
    ]
