# Generated by Django 4.2.5 on 2023-11-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='status_of_help',
        ),
    ]
