# Generated by Django 4.2.5 on 2023-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='contain_of_help',
            field=models.TextField(max_length=255),
        ),
    ]
