# Generated by Django 4.2.6 on 2023-11-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_beneficiary_bank_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_donate_summ', models.IntegerField(default=0)),
                ('count_donate_times', models.IntegerField(default=0)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.helprequest')),
            ],
        ),
    ]
