# Generated by Django 4.2.6 on 2023-12-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userdonate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonate',
            name='last_donate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
