# Generated by Django 4.2.6 on 2023-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userdonate_last_donate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonate',
            name='last_donate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
